[build]
  publish = "public"
  command = "git submodule update -f --init --recursive && npm install postcss-cli && hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.59.0"
  HUGO_ENV = "production"
  NODE_VERSION = "15.3.0"
